development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
   # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:3000/rooms/1" } %>
  channel_prefix: first_chatroom_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:3000/rooms/1" } %>
  channel_prefix: first_chatroom_production
